### ISSUE TITLE
Suppress Excessive Notices - Settings > General

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wc-calypso-bridge#1044]
There are a number of notices showing on the general Woo settings page. We can suppress them on our end but Beau also tagged Escargot here: https://hostedwoo.wordpress.com/2023/03/09/a-stroll-through-woo-express/

![Image](https://user-images.githubusercontent.com/89872780/224374334-c0b3ec74-ed3b-4713-a436-52b18cb37ff4.png)

We have another issue wp-calypso #72717 for store settings so ignore that part of the image.

**Comment by warrendholmes** [comment]
@manospsyx I know that that payments team is looking at the first notice, do you know if the other two notices are still displaying? I can't replicate them with WC Shipping and UPS rates turned on.

**Comment by manospsyx** [comment]
@warrendholmes the last two are gone because shipping extensions are disabled by default. The next logical step here would be to design a mini onboarding experience that lets merchants know they are there, prompting them to activate the one(s) they need.

Ultimately, my hope is that WooCommerce Shipping will become a one-stop-shop solution for live rates and labels, but it likely won't be able to fully replace local methods like Royal Mail.

**Comment by warrendholmes** [comment]
@manospsyx Yep, makes sense. We have a project for extensions NUX in the Airtable backlog so I'm closing this one out here.
