### ISSUE TITLE
Unify navigation in Payments and Emails

### ISSUE THREAD

**Issue by josemarques** [Automattic/wc-calypso-bridge#110]
There are a few sections that offer a "back button" navigation to return to previous lists, such as Payments and Emails:

![screen_shot_2018-10-30_at_12_12_34](https://user-images.githubusercontent.com/57050/47717289-4abfce00-dc3d-11e8-9107-50364acbe589.jpg)

But in the shipping zones a different pattern using a breadcrump is employed:

![screen shot 2018-10-30 at 12 14 48](https://user-images.githubusercontent.com/57050/47717375-7fcc2080-dc3d-11e8-943b-5ab5fffd9952.png)

Is it possible to use the breadcrumb everywhere instead of the backbutton?

**Comment by joshuatf** [comment]
There are 2 areas where I see the `wc_back_link()` being used:
* Payment settings
* Email settings

It doesn't look like there's a hook in that function or around the title, but I imagine we might be able to do a somewhat hacky solution and hook into `woocommerce_settings_tabs_' . $current_tab ` and use flexbox to reorder elements.

I can take a stab at this later today and see if I can come up with something.

@josemarques Would we want to remove the title (and description?) when we place the breadcrumbs here since the title is already included in the breadcrumbs?  Or append the breadcrumbs beneath the title?

**Comment by josemarques** [comment]
We can remove the title since it's in the breadcrumb, but I think it makes sense to keep the description.
