### ISSUE TITLE
Shipping task should not be showing in the Task List

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1144]
Since we're bypassing the store profiler, the Add shipping costs task is showing. We should use the smart shipping defaults and have users reviews their shipping costs in the Things to do next. 

_Edited by Ilyas_

### Acceptance criteria

1. Implement [smart shipping defaults logic](https://github.com/woocommerce/woocommerce/blob/4d3aa912eb908c11a2923ec29e821aa16d2a99d7/plugins/woocommerce/src/Internal/Admin/Homescreen.php#L133-L138) for the affected countries, `'CA', 'AU', 'GB', 'ES', 'IT', 'DE', 'FR', 'MX', 'CO', 'CL', 'AR', 'PE', 'BR', 'UY', 'GT', 'NL', 'AT', 'BE'` in bridge.
2. Ensure that smart shipping defaults only apply to **new stores without an existing shipping zone**
3. Override [Shipping task](https://github.com/woocommerce/woocommerce/blob/4d3aa912eb908c11a2923ec29e821aa16d2a99d7/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Shipping.php#L92) to reflect the changes to affected countries

**Comment by warrendholmes** [comment]
@ilyasfoo both @verofasulo and I seem to get it. I don't think I'm doing anything special — just creating a free trial from WooCommerce.com. 

@ilyasfoo What does your task list look like on a new trial?

**Comment by ilyasfoo** [comment]
@warrendholmes Oh, of course! I just remembered that smart shipping defaults are not applied to all countries. I have been creating my sites with the country set to US (I guess my proxy does that by default).

Currently, the following countries will not have smart shipping defaults applied: `'CA', 'AU', 'GB', 'ES', 'IT', 'DE', 'FR', 'MX', 'CO', 'CL', 'AR', 'PE', 'BR', 'UY', 'GT', 'NL', 'AT', 'BE'`.

cc @verofasulo Can you help verify if this logic is correct? As far as I remember, initially, smart shipping did not apply to only AU, CA, and GB. Then, since adding shipping partner suggestions we've added the rest of the countries so they can get the recommendation.

**Comment by verofasulo** [comment]
> Can you help verify if this logic is correct? As far as I remember, initially, smart shipping did not apply to only AU, CA, and GB. Then, since adding shipping partner suggestions we've added the rest of the countries so they can get the recommendation.

Thanks for bringing this up, @ilyasfoo! That's correct. It's something that was changed in Core due to partner promotion.

As already shared at that time, I'm not in favor of this change. I think users would benefit from a more sleek start, and numbers highlight that the shipping task is the one the user interacts less with. I would recommend removing it from Woo Express and decluttering the task list. @warrendholmes, your call 😉

**Comment by ilyasfoo** [comment]
Re-ping @warrendholmes in case you missed it

**Comment by warrendholmes** [comment]
Sorry @ilyasfoo — missed this. Yes, let's include those countries.

**Comment by ilyasfoo** [comment]
No worries, @warrendholmes! I assume you mean to remove the shipping task for all countries in Woo Express?

**Comment by warrendholmes** [comment]
Yes sir @ilyasfoo !

**Comment by moon0326** [comment]
Hey @adrianduffell ✋  Are you working on this?

**Comment by adrianduffell** [comment]
@moon0326 Yup I worked on this last cycle and finished it. I'll have a PR up next week!

**Comment by ilyasfoo** [comment]
Hey, @adrianduffell! I'd like to know if you're still working on it

**Comment by warrendholmes** [comment]
@adrianduffell @ilyasfoo What's the status of this one? I'm hoping it's an easy fix that we can resolve soon.

**Comment by warrendholmes** [comment]
@ilyasfoo Thanks for the update!
