### ISSUE TITLE
Hide Brands (and Newsletter) columns in Products list table

### ISSUE THREAD

**Issue by manospsyx** [Automattic/wc-calypso-bridge#1210]
### Description

The Brands and Newsletter columns are throwing off the table layout:

<img width="1182" alt="Screenshot 2023-06-28 at 2 16 05 PM" src="https://github.com/Automattic/wc-calypso-bridge/assets/1783726/22551f01-4cb1-4f0c-8668-a533cd44002f">

They are both of secondary importance to new users, and should be turned off by default [here](https://github.com/Automattic/wc-calypso-bridge/blob/92616f72e4a15723291499432f431184e127e90f/includes/class-wc-calypso-bridge-plugins.php#L95).

**Comment by jeherve** [comment]
> this column will not appear on the Products list for much longer, so that part will be solved

For reference, this was fixed in https://github.com/Automattic/jetpack/pull/31374 , and the fix was deployed to the Atomic platform on Tuesday evening. You should no longer see a Newsletter column on the Products screen.

> let's do the brands part :)

As far as I can tell, this is done on purpose in the WooCommerce Brands plugin:

https://github.com/woocommerce/woocommerce-brands/blob/a0dd37ca7be65440018e0bb9003b00c80b37a338/includes/class-wc-brands-admin.php#L24-L26

It may be worth reaching out to the folks on @Automattic/ventures about this, maybe this is a default behavior that could be changed in the plugin itself, instead of tackling it in wc-calypso-bridge.

**Comment by PanosSynetos** [comment]
@manospsyx  , it wasn't Brands that was causing the behavior you mention, it was Jetpack's Newsletter column, which is now gone.

Do you still want us to hide the Brands column for Woo Express sites?
