### ISSUE TITLE
Block themes do not update the heading of the My Account page based on the active tab

### ISSUE THREAD

**Issue by jimjasson** [Automattic/wc-calypso-bridge#1221]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When a block theme is used, like Tsubaki or Tazza, and I navigate to the My Account page and select the 'Orders' tab, then an 'Orders' heading doesn't show up -- the heading always read "My Account".

![RKkXEA.png](https://github.com/Automattic/wc-calypso-bridge/assets/25955483/f3119c10-a216-4ca4-bfab-f98c95d3eb7a)

If I use a different theme, like Twenty Twenty Three or Storefront, then the title of the selected tab is displayed as the header:

![CJ5FLd.png](https://github.com/Automattic/wc-calypso-bridge/assets/25955483/0c3e9593-a986-4bf4-ba6c-a36706754560)

### Expected behavior

The expected behavior is that the title of the selected My Account tab is used as the heading.

### Actual behavior

The actual behavior is that the heading of the My Account page doesn't change when a new tab is selected.

### Steps to reproduce

1. Enable Tsubaki. 
2. Ensure that your store has a couple of orders.
3. Go to the My Account page. 
4. Select the Orders tab.

### WordPress Environment

Fresh WordPress install with the latest WooCommerce, WooCommerce Blocks and Tsubaki versions.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by dinhtungdu** [comment]
@jimjasson Debugging this issue I found out that it's not completely new issue. We encountered a similar one in https://github.com/woocommerce/woocommerce-blocks/issues/10379.

The issue here is: the way WP sets up post data in block themes is a bit unreliable.

`Twenty Twenty Three` is a block theme, but it doesn't have this issue. Comparing the `page.html` template of `Tsubaki` and `Twenty Twenty Three`, I notice a different:

<img width="1262" alt="image" src="https://github.com/Automattic/wc-calypso-bridge/assets/5423135/907d86d5-a2d4-41b6-b7db-4df9dff1f2b7">

WooCommerce controls the title of My Account endpoints by filtering the `the_title` filter;

https://github.com/woocommerce/woocommerce/blob/46b687830a776a105a446d20fa63ade733a5d5ae/plugins/woocommerce/includes/wc-page-functions.php#L19-L34

Testing with the `Tsubaki` theme, I notice the `in_the_loop()` returns `false`. It returns true with `Twenty Twenty Three`.

Digging deeper to see how WP render `core/post-title` and `core/post-featured-image`, we can see the latter setups the post data if needed, the comment also explains the reason very well:

https://github.com/WordPress/gutenberg/blob/5f30adec8ec8dca924f888d9eddfe554c3ad9258/packages/block-library/src/post-featured-image/index.php#L16-L27

`core/post-title` doesn't do that, so that's why the order of block matters here.

#### What we can do from here

Fixing it theme per theme basis. I don't like this workaround but it's the quickest way we can do while waiting for more proper solution.

IMO, Gutenberg should fix this issue but I haven't known how yet. There is [an issue](https://github.com/WordPress/gutenberg/issues/32896) raised 2 years ago and hasn't been updated since then.

**Comment by dinhtungdu** [comment]
@jimjasson Affected themes like Tsubaki can use either of these following options:

- Change the position of Featured Image and Title blocks in the Page template.
- Add this code to the theme functions:
```
add_filter('pre_render_block', function ($block_content, $block) {
	if ('core/post-title' !== $block['blockName']) {
		return $block_content;
	}

	if (!in_the_loop() && have_posts()) {
		the_post();
	}

	return $block_content;
}, 10, 2);
```

**Comment by jimjasson** [comment]
Thank you @dinhtungdu for diving into this and offering a couple of alternatives! 

Pinging @xristos3490 to have a look at these when he is back from his AFK, as he has worked closely with Tsubaki.

**Comment by jimjasson** [comment]
> Change the position of Featured Image and Title blocks in the Page template.

I tested this suggestion and confirmed that the issue gets resolved: 

![GLrc3t.png](https://github.com/Automattic/wc-calypso-bridge/assets/25955483/29606c35-5b5e-4fc5-b07b-d7bc2edd1a9e)

**Comment by dinhtungdu** [comment]
I believe this issue is fixed in WP 6.4: https://github.com/WordPress/WordPress/commit/5b6555a3845818624a8dab93d57325e11e1c04e1

**Comment by sunyatasattva** [comment]
Confirming… can we close this issue, then?

**Comment by PanosSynetos** [comment]
Καλημέρα Λούτσο! Agreed, closing!
