### ISSUE TITLE
Add telemetry for the new /plugins page

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1275]
The new /plugins page doesn't have any telemetry so we're not able to understand how it is impacting conversions.

We should just replicate how we track the Extensions page:

- Add a wcadmin_plugins_view event (On the extensions page we have https://mc.a8c.com/tracks/live/?eventname=wcadmin_extensions_view)
- Fire the wcadmin_page_view event too
- Implement tracking on the various CTAs on the page.

**Comment by xristos3490** [comment]
> Implement tracking on the various CTAs on the page.

We do have tracking for CTAs as described here: https://github.com/Automattic/wc-calypso-bridge/blob/c5becc5a816ee2298fcab73df82ccb2ec294e6f4/includes/templates/html-admin-page-plugins-landing-page.php#L87-L115

> In Plugins page, it seems like a native WordPress page

Yup! This is a native WP page. Should we consider implementing this as part of the WCA? Would the `wcadmin_plugins_view` be easier to implement following that path? cc @ilyasfoo

**Comment by moon0326** [comment]
@xristos3490 @ilyasfoo  It looks like we already have `recordEvent` function available on the page. I don't think we need to implement the page as a part of the WCA in that case.

**Comment by ilyasfoo** [comment]
> Yup! This is a native WP page. Should we consider implementing this as part of the WCA? Would the wcadmin_plugins_view be easier to implement following that path? cc @ilyasfoo

@xristos3490  I think it would be the ideal scenario to implement this as part of WCA, but I'm unsure how easy it is. I believe the code responsible to add it lies somewhere in [this PHP](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/react-admin/connect-existing-pages.php), if it's easy to implement in bridge I would recommend it. Otherwise, perhaps implementing `wcadmin_plugins_view` independantly would be the alternative.

> @xristos3490 @ilyasfoo It looks like we already have recordEvent function available on the page and we have access to WC_Tracks::recordEvent(). I don't think we need to implement the page as a part of the WCA in that case.

> We do have tracking for CTAs as described here:

@xristos3490 @moon0326 Sorry the issue description was not accurate, CTA tracks are already implemented, only the pageview track is missing, where adding the page into WCA would accomplish without manually firing the track.

**Comment by moon0326** [comment]
> Adding the page into WCA would accomplish pageview track without manually firing it.

We can also manually fire those two tracks unless we have other reasons for adding the page to WCA.

**Comment by moon0326** [comment]
@ilyasfoo 👍  I'll spend a couple of hours tomorrow and see how difficult it is to add the page into WCA. It'll benefit us for future pages.

**Comment by moon0326** [comment]
@ilyasfoo @xristos3490 I've opened a https://github.com/Automattic/wc-calypso-bridge/pull/1278 to convert the plugins page into a WC page. I'll document the steps [here](https://github.com/Automattic/wc-calypso-bridge/wiki/How-To) (WIP)
