### ISSUE TITLE
Remove Blog from the pages generated by default on Woo Express

### ISSUE THREAD

**Issue by PanosSynetos** [Automattic/wc-calypso-bridge#1321]
As discussed in 
- https://github.com/woocommerce/woocommerce-blocks/issues/11253

@verofasulo asked

> could we please remove Blog from the pages generated by default on Woo Express, please?

To give some feedback, blog page is generated by Tsubaki's headstart. It also creates a blog post. See

https://github.com/Automattic/theme-tsubaki/blob/trunk/inc/headstart/en.json#L278-L292 
and 
https://github.com/Automattic/theme-tsubaki/blob/trunk/inc/headstart/en.json#L20-L36

On Woo Express, currently, we don't delete this page, all we do is add it to the menu
https://github.com/Automattic/wc-calypso-bridge/blob/ef3b3ae7c16caff0aaae0a0b6e1329c351bc7a08/includes/class-wc-calypso-bridge-setup.php#L371

### Questions

1. If we delete blog, do we also delete the post?
2. Do you want us just to remove blog from the menu, and leave blog and the post as it is?

cc @manospsyx

**Comment by manospsyx** [comment]
Hey folks 👋 

> could we please remove Blog from the pages generated by default on Woo Express, please?

Do we have any data around this? Many merchants are likely to choose Woo because of the blogging capabilities of the WP platform. I agree that the word "blog" might be off-putting to some in 2023; many merchants may feel more "at home" with a re-wording to "News" here. 

Keep in mind that the back-end strongly emphasizes the blogging capabilities of the platform anyway (e.g. "Posts" menu item). The Site Editor is notoriously difficult to use to customize the menu -- are we confident there's an easy way to add this? 

I'd be in favor of dropping the Blog menu item, but only after we have shipped a store personalization experience that allows merchants to easily surface a news/posts menu item (and perhaps even give it a name). 

cc @verofasulo

**Comment by verofasulo** [comment]
Hey @manospsyx 👋

> Do we have any data around this?

That's a great question! Any chance we can get some data about the % of live Woo Express stores without the Blog page? cc @adrianduffell @ilyasfoo 

> Many merchants are likely to choose Woo because of the blogging capabilities of the WP platform.
Keep in mind that the back-end strongly emphasizes the blogging capabilities of the platform anyway (e.g. "Posts" menu item). The Site Editor is notoriously difficult to use to customize the menu -- are we confident there's an easy way to add this?

That's interesting. My assumption was different—most of new merchants that are opening a store in Woo Express are not interesting in blogging. I see it as something related to another use case, e.g. users that are coming from WordPress, already have a blog, and decide to build a store on it.

**Comment by ilyasfoo** [comment]
@verofasulo Good question. Unfortunately, I wasn't able to find any related tracks we fire that could be used to count the number of sites without the Blog page.

However, as a proxy, Jetpack powered sites may store the data on trashed/unpublished posts and pages. I suspect the data might be available somewhere in Jetpack's activity log, but I doubt it'll be a small endeavour to dig through and link everything up.

**Comment by verofasulo** [comment]
@ilyasfoo, thanks for investigating further! 💜

Do you think it would be possible to add this tracking event from now on? cc @adrianduffell @SamratBiswas1

**Comment by ilyasfoo** [comment]
@verofasulo I believe it's possible but it's not straightforward. The blog page can be "removed" by 3 actions: delete, rename, and unpublish.

I think we'll have to add a track to relevant hooks to all these actions with appropriate check on the blog name or meta data. After that, in order to find out how many % of users remove the Blog page, we may need to compare the numbers of free trial sites created since the track is added with the number of users who fired the remove tracks.
