### ISSUE TITLE
Free trial days JITM not showing up in wp-admin context

### ISSUE THREAD

**Issue by PanosSynetos** [Automattic/wc-calypso-bridge#1370]
Free trial JITM doesn't show up in wp-admin pages. It only shows up in Calypso pages.

We had a similar issue back in June 2023 #1196 
- #1196 
But back then it was not consistently replicated and @markbiek . Now it seems to be consistent. I just fired up a new site and it happened

### wp-admin free trial
![image](https://github.com/Automattic/wc-calypso-bridge/assets/2484390/80c46cc6-1cac-4a0c-aba7-ba7af81fbf71)

### calypso free trial

![image](https://github.com/Automattic/wc-calypso-bridge/assets/2484390/9c239678-5c7e-44f8-b3b4-819ddaa42b03)

@ilyasfoo I've assigned this to you, as you offered to investigate. Feel free to reassign this to the proper team if needed

Thank you @oneillo for pinging us

**Comment by tckasa** [comment]
@ilyasfoo @PanosSynetos @danielbachhuber While investigating the drop in free-to-paid CVR, specifically the significant drop from My Home Visitors to the Plans Page, I [signed up for a new trial account](https://woo-delicately-wise-peace.wpcomstaging.com/wp-admin/admin.php?page=wc-admin) and noticed that the Free trial days JITM didn't appear when I first landed on My Home. However, if I navigate to any other page and return to My Home, it shows up normally.

I'm not asserting that this is the root cause of the performance drop, but it's worth exploring whether this issue consistently occurs when users create new free trial accounts.

Furthermore, be aware that the 'calypso_wpcom_jitm_ecommerce_trial_impression' is fired when clicking on this JITM, not as it is intended to work when it is displayed.

For additional context on performance, [refer to the comment linked here](https://hostedwoo.wordpress.com/2023/12/01/woo-com-domain-migration-impacting-nux-traffic/#comment-5285).

![Screenshot on 2023-12-07 at 17-22-51](https://github.com/Automattic/wc-calypso-bridge/assets/93389286/80b8949e-219a-44e5-920a-4aa6f578f494)

cc @Timstreep @SamratBiswas1

**Comment by PanosSynetos** [comment]
A new issue would be great, if there is a need to check further.

But, giving my two cents here, this seems to happen as behind the scenes not everything is synced the moment the redirect happens to the new site.

That's why the message does not appear (SOMETIMES) during the first visit, and then after a minute the JITM shows up.

**Comment by ilyasfoo** [comment]
I agree with @PanosSynetos. I've been able to observe the issue with new sites where sync isn't finished.

I can't think of a simple fix for it since it's dependant on Jetpack's sync and we don't want the user to be waiting too long in the loading screen. Perhaps one way is to poll for sync status and retry JITM request when it's done, but IMO it feels not ideal.

**Comment by danielbachhuber** [comment]
What is the data that needs to be transferred? Maybe we could move that to much earlier in the transfer process?

**Comment by ilyasfoo** [comment]
@danielbachhuber I don't know for sure but I think it's the subscription/plans data that's pending. For more context, D98477-code contains the code we use to generate the nudge in `wpcom_ecommerce_trial_rules` (I can't find a way to properly link to the file from public repo).
