### ISSUE TITLE
Email templates out of date

### ISSUE THREAD

**Issue by mikkamp** [Automattic/wc-calypso-bridge#18]
The email-order-details.php template is being overridden, see: https://github.com/Automattic/wc-calypso-bridge/blob/master/inc/email-templates/email-order-details.php

This email template is very different then the latest one in WooCommerce: https://github.com/woocommerce/woocommerce/blob/3.2.5/templates/emails/email-order-details.php

Main differences are, the order date shown next to the order number and the order notes which are included in the email. Both of these don't show up when an email is sent from WooCommerce containing order details.

From what I can see the main reason this template is overridden is to change the order link for admin users. Wouldn't it be better to get WooCommerce to include a filter for that, so it can be adjusted without having to override the template?

Also the URL override seems to make sense for users who have a Shop on WP.com but I'm not sure if this would work the same for regular users who have a plain AT site and install WooCommerce. Is there a way to differentiate between the two?

Affected ticket: 835837-zen

**Comment by timmyc** [comment]
Hi @mikkamp thanks for opening this up, sorry I seemed to have missed it last month.

> From what I can see the main reason this template is overridden is to change the order link for admin users.

Yes that is the only reason why have this over-ridden currently.

> Wouldn't it be better to get WooCommerce to include a filter for that, so it can be adjusted without having to override the template?

Absolutely having a filter would be a much better solution... might be worth opening an issue on Woo core for this - though I really wonder how many other users would want to filter the admin order edit URL value 🤔 

> Also the URL override seems to make sense for users who have a Shop on WP.com but I'm not sure if this would work the same for regular users who have a plain AT site and install WooCommerce. Is there a way to differentiate between the two?

This is another excellent point. I believe we set an option on the site when the install is done via Calypso/Store ( but that option is escaping me now, @justinshreve do you happen to know it? ) - so if we did have the filter available we could be a bit more selective on when we use a calypso link vs a standard wp-admin link.

This will be even more important as we open up the new signup flow on WPCOM for non US/CA users which will install Woo and direct them to use wp-admin instead of Calypso if their country is not fully supported in Calypso.

**Comment by mikkamp** [comment]
Thanks for updating the template @timmyc 

Overriding the template isn't necessarily a problem as long as you have some kind of system in place to make sure it stays up to date with the latest version of WooCommerce.

The reason I suggested the filter was mainly for the following reasons:
- User tries to override the template in their child theme. This was tried by the user, but it seems the calypso-bridge template override has priority.
- If the user installed WooCommerce manually they will also need to update manually. Which could cause a version / template mismatch with the one being used in calypso-bridge.

The amount of users that might be doing this would probably be small. But it does take some work to track down what is causing the behaviour difference if you aren't aware of the calypso-bridge code.

**Comment by timmyc** [comment]
Great to know the origin of this issue, and interesting that over-riding the template in a child theme would not take precedence over the plugin. I will open an issue in core and see if a filter would be an option here since it definitely seems like the best solution.

Until then, we will do a better job of keeping this template current - or even possibly consider if this over-ride is really that critical by maybe adding some tracking logic on the URL to see how frequently the link is even clicked.

**Comment by timmyc** [comment]
The new template has shipped so I'm going to close this out - I added #25 to leverage the new filter and remove the email over-rides.
