### ISSUE TITLE
[Product Vendors] Commissions search broken

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wc-calypso-bridge#224]
The search box seems broken on the product vendors commissions page. It still works on other pages like orders.

<img width="925" alt="screen shot 2018-11-19 at 9 32 58 am" src="https://user-images.githubusercontent.com/689165/48713426-3d638700-ebde-11e8-8ae8-970c45dc7681.png">

**Comment by joshuatf** [comment]
@justinshreve I don't think there's a search box on this page.  (This page, right? - `wp-admin/admin.php?page=wcpv-commissions`)

The abnormalities here are probably due to the double wrapped subnav which an issue is open for here - https://github.com/woocommerce/woocommerce-product-vendors/pull/430/files

**Comment by timmyc** [comment]
I think it might be the order search box seen here:

![image](https://user-images.githubusercontent.com/22080/48850050-8e998500-ed5c-11e8-850b-27e9991209fa.png)

which is still shown, and working in my testing:

![image](https://user-images.githubusercontent.com/22080/48850131-cbfe1280-ed5c-11e8-84a5-a853619fcfe4.png)

the big issue is the label of order# is kind of lost with the new style, so the search box does seem a bit confusing.
