### ISSUE TITLE
Plugin page is not fully Calypsoified

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#306]
Looks like the `calypsoify.css` stylesheet is not being loaded and notices, inputs, etc. are not styled properly.

<img width="1604" alt="screen shot 2018-11-26 at 11 48 48 am" src="https://user-images.githubusercontent.com/10561050/48992160-6604f700-f171-11e8-9b49-c23c1a470a9a.png">

**Comment by justinshreve** [comment]
Just as some background: We intentionally gated our styles to WooCommerce now for the initial roll-out. Mainly so we didn't have to worry about compatibility with plugins outside of the eCommerce catalog, since all plugins are Calypsoified as well, and because of time.

I agree that things should look consistent though. I think the best way to go about this, once the dust has settled, is to take out some styles and create Jetpack PRs for getting notices, etc as part of the core Calypsoify package.

**Comment by psealock** [comment]
This no longer applies because we're removing Calypsoify
