### ISSUE TITLE
Make required plugins "managed" installs

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#34]
During the last update period where both `woocommerce` and `woocommerce-gateway-stripe` were updated, the thousands of Atomic Store sites with these plugins installed created a bit of a DDOS scenario when they all were auto-updating their local installs of the plugins.

@seanosh would like for us to have any plugin that we install during the Store setup process be a managed/sym-linked plugin - much like how Jetpack is managed on Atomic sites.

Some prior chatter and investigation on the subject: p1517610636000358-slack-auto-transfer-dev

In my quick look into how to potentially handle this - I didn't see an easy spot to hook into the existing plugin install flow ( handled by Jetpack ) to do a symlink/managed install vs a standard plugin install.

Furthermore we need to consider how we can retroactively apply this change to the existing installs of these plugins.

Also are there any things we need to be aware of / concerned about when considering making these plugins "managed"

@seanosh - just curious but aren't there other popular plugins that could lead to the same situation on AT sites?

**Comment by seanosh** [comment]
> @seanosh would like for us to have any plugin that we install during the Store setup process be a managed/sym-linked plugin - much like how Jetpack is managed on Atomic sites.
> In my quick look into how to potentially handle this - I didn't see an easy spot to hook into the existing plugin install flow ( handled by Jetpack ) to do a symlink/managed install vs a standard plugin install.

Because this is a unique requirement/constraint to Atomic, it should probably be handled via WPcomSH. Whether it's some function that symlinks whatever plugin names that are provided to it or if there's some other means can be best worked through there and with the Atomic team's involvement.

> Furthermore we need to consider how we can retroactively apply this change to the existing installs of these plugins.

I'll deal with this part when the above is tackled and deployed. That way I can narrow the scope of what sites need to have the plugin folder removed and atomically replaced with the symlink. 

> Also are there any things we need to be aware of / concerned about when considering making these plugins "managed"

I don't think so unless any of them try to write to a file/folder within each plugin. Since the symlink points to a "read only" copy of the latest version of the plugin, this wouldn't be possible.

> @seanosh - just curious but aren't there other popular plugins that could lead to the same situation on AT sites?

I'm sure there are, but none of them are causing or have caused the problems that these plugins have :)

**Comment by timmyc** [comment]
This is being handled by the Atomic team, closing.
