### ISSUE TITLE
Orphan | at the end of the extension categories.

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wc-calypso-bridge#362]
![](https://cldup.com/zASE2VCVKO-3000x3000.png)

via p58i-7nL-p2  #comment-40299

**Comment by joshuatf** [comment]
I'm thinking we should probably remove those altogether since they aren't consistent with the other subnavs.

<img width="455" alt="screen shot 2018-11-29 at 4 55 28 pm" src="https://user-images.githubusercontent.com/10561050/49210307-b1c8d200-f3f7-11e8-8fb8-58045d1f647b.png">
<img width="426" alt="screen shot 2018-11-29 at 4 55 50 pm" src="https://user-images.githubusercontent.com/10561050/49210309-b2616880-f3f7-11e8-9447-3e6e052755e8.png">
