### ISSUE TITLE
Single order date and time width

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#387]
The hour and minute inputs are broken into 2 separate lines. 
<img width="254" alt="screen shot 2018-11-30 at 11 01 21 am" src="https://user-images.githubusercontent.com/10561050/49265999-682bc600-f48f-11e8-8ab3-60f18f66f423.png">
IE11:
<img width="261" alt="screen shot 2018-11-30 at 11 03 32 am" src="https://user-images.githubusercontent.com/10561050/49266047-a0cb9f80-f48f-11e8-8e1b-4d45164276b9.png">

I think we should make the date the full width and keep a separate line for the times.  Does this look better or any other suggestions @josemarques ?

<img width="268" alt="screen shot 2018-11-30 at 11 01 11 am" src="https://user-images.githubusercontent.com/10561050/49266020-7f6ab380-f48f-11e8-9ce3-e2eed5389f05.png">

**Comment by josemarques** [comment]
@joshuatf instead of doing that can we change the breakpoint so that it wraps the billing and shipping columns under so that there's always enough room for those fields to stick together? 

![screen shot 2018-11-30 at 11 52 40](https://user-images.githubusercontent.com/57050/49287802-b1334880-f496-11e8-8f2e-0d61db201e04.png)
