### ISSUE TITLE
Onboarding - Store Profiler: Hide the option "CBD and other hemp-derived products"

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#573]
WordPress.com doesn't support CBD, so the option `CBD and other hemp-derived products` should be removed from the Industry step in the eCommerce plan.

**Comment by becdetat** [comment]
Estimate: 1

**Comment by octaedro** [comment]
Hi @pmcpinto,
I'm working on this issue now. I wanted to ask you:
What happens when the client with the eCommerce plan already has the option `CBD and other hemp-derived products` set? Is it ok if we treat the client as if they have never selected that option?

It looks like hiding the option when the client is using `calypso-bridge` will be enough in order to solve this issue.

**Comment by pmcpinto** [comment]
> What happens when the client with the eCommerce plan already has the option CBD and other hemp-derived products set? > Is it ok if we treat those clients as if they have never selected that option?

Yes, I think we should keep it simple and treat it as if they never selected the option. AFAIK we only have 1-2 cases.
