### ISSUE TITLE
Remove usage tracking auth message

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#574]
On the eCommerce plan we're not required to display the authorization message, so the modal should be removed: https://cloudup.com/c1mhDuaiFe2

 #534 was supposed to cover this change, but the modal continues being displayed.

**Comment by pmcpinto** [comment]
cc @timmyc

**Comment by timmyc** [comment]
Pedro I think we need to move this issue to wc-admin... the reason it couldn't be removed in #534 was there is no way for us to filter/hide this modal from outside of wc-admin. My initial idea was to simply not show the modal if the site has already opted in to usage tracking. On the ecommerce plan, since this setting will always be true, it will make the modal disappear.

**Comment by pmcpinto** [comment]
@timmyc ah ok, I thought that it was possible to hide the modal in the eCommerce plan without any change in the WCAdmin side. 

So in order to start hiding the modal in the eComm plan, we need to wait for this to be merged and released in Core, correct?
