### ISSUE TITLE
eComm onboarding - store profiler: don't redirect users to wp-admin

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#608]
Users are being redirected to wp-admin after completing or skipping the profiler: https://www.loom.com/share/6d8ee5e2d77a48d69caf73c19f47248d
They should be redirected to WooCommerce within Calypso.
This seems to be a regression as it was working fine before this release.

**Comment by timmyc** [comment]
This is looking like the same reason noted in #607 - and just wanting to confirm with you, you saw this behavior the same time you encountered the extensions being shown too.

The links from calypso -> ecomm all have the &calypsoify=1 param on them so that is what we have always leaned on to make this work. Seems like you hit a flow that dropped you out into wp-admin initially and cleared the calypsoify setup.

I'm hesitant to add in stronger logic that always redirects users to calypsoify for the OBW right now, given that we are going to be changing things in that space soon for the nav project. But again we could consider doing that by adding some logic that:

- Detects if a site is ecomm plan
- If the profile wizard is being loaded, force a redirect with a `&calypsoify=1` on the URL, or break out all of our css and logic tweaks into stand-alone files to always load on the profiler pages.

**Comment by pmcpinto** [comment]
@timmyc yep, I think you're right.

I just created a new store and I came across this weird bug: https://www.loom.com/share/43fa4e6b929147a5bfb25104728caff6

Then I went to the Calypso Home and I was redirected to the store profiler after clicking on the Store option: https://www.loom.com/share/aa21761b875044d8b8ca514bcc5dadf7
Everything seems to be working properly, the only exception is the monthly pricing toggle (#606) and the skip link in the first step of the profiler - this was the reason why I was redirected to wp-admin when I tested the flow this morning.

**Comment by timmyc** [comment]
> and the skip link in the first step of the profiler

So should we remove the skip link?

The error you encountered almost looked like the new site wasn't fully provisioned yet, and your account hadn't been given access to it. If you could when you record screen grabs like that, include the address bar, but I'm guessing the URL was that for the site profile wizard, would have been good to confirm.

**Comment by pmcpinto** [comment]
@timmyc I was testing again the flow and this is already the 2nd time since 4.6 was shipped that I'm getting this error when I try to access the onboarding after completing the purchase: https://www.loom.com/share/2c10163bdb4147099bd908284d65d46e

I think that this is probably related to the old onboarding removal and the splash screen redirect. Do you want me to open a new issue about this? I'm afraid that any new user is seeing this 😞 

PS: I clicked in the skip link and I wasn't redirected to wp-admin
