### ISSUE TITLE
Hide theme selection in woo onboarding

### ISSUE THREAD

**Issue by lsl** [Automattic/wc-calypso-bridge#769]
Refresh of https://github.com/Automattic/wp-calypso/issues/55406

Implemented in https://github.com/Automattic/wc-calypso-bridge/pull/732

- [ ] Retest
- [ ] Merge

**Comment by louwie17** [comment]
Hi @lsl,
Where you hoping to re-add the logic referenced in #732? Do you happen to have more context on why the themes step should be hidden again?
cc'ing @pmcpinto so that you are also aware of this.

**Comment by lsl** [comment]
@ianstewart might be able to answer that question better. Eventually we'll be dropping the onboarding flow entirely in favor of one that happens in calypso, the new flow won't include a theme step. We'll be using it for a little while until we've finished building out the new flow.

**Comment by joshuatf** [comment]
I'd love to get more context on this.

>Eventually we'll be dropping the onboarding flow entirely in favor of one that happens in calypso

I assume we're only talking about ecomm/atomic plan sites here.  In which case we're looking at a way to disable and/or filter pieces of the onboarding.

cc @ianstewart @pmcpinto

**Comment by lsl** [comment]
It will eventually be all wpcom plans but yes, not talking about replacing it for general woo installs.

We're going to be using the same questions and setting the same options after transfer as if the user went through the profile wizard.

At a later date - we might want to try and port the new design / step components into woo's admin plugin too but that is very far off.

**Comment by joshuatf** [comment]
Will this be synced with the `woocommerce_onboarding_profile` option or is information strictly held in Calypso?

It may be of some benefit to create a data store or simple API for setting/retrieving profile information if it's going to be shared to prevent data from becoming corrupt.

**Comment by lsl** [comment]
> Will this be synced with the woocommerce_onboarding_profile option

Yes

I tried to convey some more context on p2 earlier today pbIJXs-143-p2#comment-3122, this might help understand what and why. 

> It may be of some benefit to create a data store or simple API for setting/retrieving profile information if it's going to be shared to prevent data from becoming corrupt.

This sounds like a good idea, I don't know how much of a problem it really is in practice but the onboarding changing in woo and breaking our onboarding (or at least making it not take effect) is a bit of a concern I have with this approach.

**Comment by pablinos** [comment]
Is this a blocker that prevents us launching the flow this cycle? It seems like it's an improvement, that's not needed right now. Is that the case @lsl ?

**Comment by joshuatf** [comment]
IMO this is not a blocker and we do directly modify via options around WooCommerce Admin, but this code would be brittle and prone to corruption should the data structure ever change in the onboarding profiler.

This has happened in the past with the industries data schema changes.

Since you may be looking at hiding steps or completing the baked in Woo onboarding early, it sounds like you'll be modifying the `skipped` or `completed` bools.  These are relatively stable so I don't anticipate too many issues, but in a worst case scenario this would require store owners to re-complete the onboarding profiler after have already established stores.

It's probably okay to proceed with caution, but I'd like to see this updated to use a more formalized API in the near future as opposed to directly modifying the options data.

**Comment by obenland** [comment]
Fixed in https://github.com/Automattic/wc-calypso-bridge/pull/732
