### ISSUE TITLE
Add `@wordpress/base-styles` support

### ISSUE THREAD

**Issue by chihsuan** [Automattic/wc-calypso-bridge#941]
Add `@wordpress/base-styles` support to use Gutenberg color variables in bridge

https://github.com/WordPress/gutenberg/tree/79103f124925d1f457f627e154f52a56228ed5ad/packages/base-styles

**Comment by xristos3490** [comment]
We do include the https://www.npmjs.com/package/@automattic/color-studio package.
Take a look at the available colors here: https://color-studio.blog/
Here's an existing example: https://github.com/Automattic/wc-calypso-bridge/blob/master/src/launch-store/style.scss#L1-L20

Could that work instead of the base styles?

**Comment by xristos3490** [comment]
Of course, if we are aiming for other stuff, like mixins and functions, adding this package might be a great idea!

**Comment by chihsuan** [comment]
Hey @xristos3490 Thanks for looking into it. 🙂 

> Could that work instead of the base styles?

Glad to know that! Unfortunately, I think we still need Gutenberg colors for the free trial components. 😞 

> Of course, if we are aiming for other stuff, like mixins and functions, adding this package might be a great idea!

Yep! 🙌
