### ISSUE TITLE
Task: Update custom product creation task to detect modified products

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wc-calypso-bridge#973]
In #963, we're overriding the "Create a product" task from WooCommerce core to ignore products that are created by the WordPress.com Headstart tool. However, users may choose to modify the existing products instead of creating new ones. We should consider enriching our custom logic to detect when users have updated the sample products so we don't leave the task as incomplete.

**Comment by ilyasfoo** [comment]
Would this be a 100% or 10% launch requirement?

**Comment by daledupreez** [comment]
> Would this be a 100% or 10% launch requirement?

I think it qualifies as a nice-to-have for the 10% launch, so it may or may not make it. I think it depends on what other items we have queued up for the 10% launch.

**Comment by manospsyx** [comment]
Might be a good idea to take a step back and explore the problem a bit more before diving into a solution. WooCommerce already provides a path in the onboarding flow that lets users create sample/demo products.

I'm not familiar with how Headstart works but it currently seems to be completely isolated from the Core onboarding experience, which I believe is the root cause of the problem here :) 

- New merchants will probably want to decide during onboarding if they want to take a look at demo content or not. 
- A prompt to decide should be surfaced inside the "Add products" task (in fact, there's already a prompt there).
- If merchants decide to create demo content at that point, the task should appear as completed (as it does now).

Ideally, demo content should be tailored to the theme, but the entire experience needs to be designed with the existing onboarding flow in mind. The implementation should be implemented hand-in-hand with the WooCommerce core codebase, adding extensibility when/if needed.

Given that WooCommerce core already prompts the user to create demo products, what is the problem the Headstart implementation solves in this context?

**Comment by ilyasfoo** [comment]
Good question, Manos. I think providing the full experience via theme makes sense. However, for the context of our launch, I think it'll be an unknown that I don't think we have the resources to investigate. I'm thinking if the solution for detecting is trivial, we may do this for launch and address the core issue at appropriate places as a follow-up. What do you think?

**Comment by daledupreez** [comment]
> Given that WooCommerce core already prompts the user to create demo products, what is the problem the Headstart implementation solves in this context?

I think the biggest issue is that it solves a different problem to onboarding. In onboarding, we want to ensure that users know how to create a new product, and get familiar with the product creation and modification workflow. Headstart is intended to solve a different problem: how do you create starter content for an eCommerce website that accurately reflects a usable starting point? Because we're on an eCommerce site, we want to show off the overall look of the site with demo products in place, as users have no way of clearly visualising what their products will look like in the context of the store without having created the products first.

This task is focused on a more short-term goal: how can we ensure that users are guided through the product creation workflow when we already have starter content on the site?

Unfortunately, the problem of jump-starting site design and layout is a much more complex issue in WordPress itself, which is why we still have the Headstart tool. I would also _love_ to remove it entirely, but without much better site creation tools (and onboarding to those tools), I don't know that we have the bandwidth or time to tackle that bigger problem.

> Ideally, demo content should be tailored to the theme, but the entire experience needs to be designed with the existing onboarding flow in mind.

I think we also need to be careful about assuming users will complete the flow in a specific order. Given that the site design is important to users, some may want to look at that much sooner, in which having starter content makes that much easier. The other gotcha is that we _do_ want a decent amount of the other starter content from Headstart (e.g. the home page content).

**Comment by that-mike-bal** [comment]
Assuming this post is related https://themedevp2.wordpress.com/2023/04/04/headstart-and-woocommerce-themes/

**Comment by that-mike-bal** [comment]
@adrianduffell is this something your team can look at?

**Comment by adrianduffell** [comment]
@that-mike-bal Yes we can take this one 👍

**Comment by ilyasfoo** [comment]
A possible solution is to use `_edit_last` postmeta to detect a product that's been modified by a user. As per ChatGPT suggestion:

```php
public static function has_products() {
  $product_query = array(
    'post_type' => 'product',
    'post_status' => 'publish',
    'fields' => 'ids',
    'meta_query' => array(
      'relation' => 'OR',
      array(
        'key' => '_headstart_post',
        'compare' => 'NOT EXISTS'
      ),
      array(
        'key' => '_edit_last',
        'compare' => 'EXISTS'
      )
    )
  );
  $products = get_posts( $product_query );
  $product_count = count( $products );

  return $product_count > 0;
}
```
